### PR TITLE
Add troubleshooting link to error message

### PR DESCRIPTION
**Pull request by milesfrain**
Follow-up to https://github.com/purescript/purescript.github.io/pull/146

### CODE REVIEW

**Comment by milesfrain** [comment]
I make a few attempts at testing this by trying to force an execution of `showError`, but this isn't trivial. Open to suggestions. I'd like to avoid uninstalling dependencies on my machine or firing-up a docker instance.

Also, some code comments would make this a lot easier to contribute to.

**Comment by hdgarrood** [comment]
I think this ought to be tested in Docker or some kind of virtual machine. This kind of code is too fiddly/sensitive to minor changes in the environment to get much confidence from any kind of testing other than proper integration testing, in my experience.

**Comment by hdgarrood** [comment]
I agree that comments would be good, but realistically I’m not going to be the one to write them; there are far too many other purescript things that are more deserving of my attention. I’d also like to rewrite this project in PureScript, which hopefully would make contributing easier (at least for people who know PureScript), but again I’m unlikely to find time for that any time soon.

**Comment by milesfrain** [comment]
Here are the docker test results:

Setup:
(seems easiest to just do this interactively instead of with dockerfile)
```
docker run -it ubuntu

cd /home
apt update
apt -y install curl git
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
nvm install 13

git clone --branch troubleshooting-link https://github.com/milesfrain/npm-installer.git
cd npm-installer
npm link

cd ..
mkdir test-installer
cd test-installer
npm init -y
npm link purescript-installer

npx install-purescript
```

Produces error with troubleshooting link as expected:
```
✔ Check if a prebuilt 0.13.0 binary is provided for linux (1s)
✔ Download the prebuilt PureScript binary (753ms)
✖ Verify the prebuilt binary works correctly
  /home/test-npm-installer/purs --version
  Error: Command failed: /home/test-npm-installer/purs --version
/home/test-npm-installer/purs: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)

See troubleshooting suggestions in https://github.com/purescript/purescript/blob/master/INSTALL.md
▬ Save the downloaded binary to the npm cache directory

↓ Fallback: building from source

✖ Check if 'stack' command is available
  stack --allow-different-user --numeric-version
  Error: Command failed with exit code 2 (ENOENT): stack --allow-different-user --numeric-version
spawn stack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

See troubleshooting suggestions in https://github.com/purescript/purescript/blob/master/INSTALL.md
▬ Download the PureScript 0.13.0 source
▬ Ensure the appropriate GHC is installed
▬ Build a binary from source
▬ Save the built binary to the npm cache directory
```

Now the interesting part is that ONLY installing `libtinfo5` will resolve the missing `libtinfo.so.5` error. Installing `libncurses5-dev` will not help (on Ubuntu 20.04). Updated https://github.com/purescript/purescript/pull/3903 with more specific instructions.

PS. For merging commits, I'd suggest "squash and merge" (which also includes a rebase) for the cleanest linear commit history.

**Comment by hdgarrood** [comment]
Thanks!

**Pull request merged**
